### PR TITLE
feat: add all subaru vehicles from appendix a

### LINKED ISSUE #25: Add all Subaru vehicles to common.js
Find all Subaru vehicles in Appendix A of this document https://www.scca.com/downloads/49336-2020-solo-rules-complete-reduced-2020-03-16/download and add them to https://github.com/Bjorn248/scca_classifier/blob/master/common.js in a similar way to other Makes.

### PR DESCRIPTION
**Pull request by burzynnn**
Fixes #25

### CODE REVIEW

**Comment by Bjorn248** [comment]
This is kind of an outlier, but can you also add the `ssc` class where possible? See page 177 of the rules. 2013 to 2016 BRZ models are eligible for this class. Also would it be possible to update your master to resolve the merge conflicts?

**Comment by burzynnn** [comment]
i can add a `ssc` class but it is from appendix k. isn't that a problem?

**Comment by Bjorn248** [comment]
SSC is a class with only 1 car model, so it's not listed with the other classes in appendix A. It is an exception.

**Comment by burzynnn** [comment]
I'm having problem with updating master. Will it be ok if I create new fork and new pull request?

**Comment by Bjorn248** [comment]
@burzynnn that's fine, I can try to resolve the merge conflicts.

**Comment by Bjorn248** [comment]
@burzynnn it looks like the github conflict resolve UI can't handle this, so yeah, please close this PR and open a new one. Thanks! And sorry for the trouble.

**Pull request closed without merging**
