### PR TITLE
Added Saturn models and classes

### PR DESCRIPTION
**Pull request by ejleitzke**

### CODE REVIEW

**Comment by Bjorn248** [comment]
There's some kind of mismatch with your local editor and the original file, causing this to be a huge diff. If this was done on windows make sure that the editor you are using has newlines set to be linux compatible. Although, it's probably whitespace. Make sure your editor is set to use spaces instead of tabs and that you have 1 tab set to 2 spaces. 

I can also just take the Saturn block out myself and add it to the file myself. Let me know what you'd like to do @ejleitzke . Thanks for the PR!

**Comment by Bjorn248** [comment]
Also, I think this might be misnamed as you are actually adding Saturn, not Pontiac, correct? This resolves #14

**Comment by ejleitzke** [comment]
> There's some kind of mismatch with your local editor and the original file, causing this to be a huge diff. If this was done on windows make sure that the editor you are using has newlines set to be linux compatible. Although, it's probably whitespace. Make sure your editor is set to use spaces instead of tabs and that you have 1 tab set to 2 spaces.
> 
> I can also just take the Saturn block out myself and add it to the file myself. Let me know what you'd like to do @ejleitzke . Thanks for the PR!

Oh wow, I just took a look at that. The whole thing is "different" lol. Let me see if I can resolve this correctly first that way it will be easier to keep contributing. 

Also, I have no idea why I put Pontiac, I blame Justin and his Solstice obsession lmao. He was probably talking about it while I was doing this.

**Comment by ejleitzke** [comment]
Also, you are a tabs guy. We can keep working together! lmfao

**Comment by ejleitzke** [comment]
Closing this request and trying again - want to make sure this references the correct issue # as well.

**Comment by Bjorn248** [comment]
> Also, you are a tabs guy. We can keep working together! lmfao

I try to conform to whatever the language norms are. For Go the standard is tabs, but for javascript it seems to be 2 spaces. I just go with the flow. I figure for JS it doesn't matter too much anyway since it will be minified in most cases.

**Pull request closed without merging**
